public without sharing class Integrated_Email_List_Constants{
    
    static public String EMAIL_STATUS_PENDING = 'Case Pending';
    static public String EMAIL_STATUS_RESOLVED = 'Case Resolved';
    static public String EMAIL_STATUS_UNRESOLVED = 'Case Unresolved';
    static public String EMAIL_STATUS_NEW = 'New';
    static public String EMAIL_STATUS_READ = 'Read';
    static public String EMAIL_STATUS_REPLIED = 'Replied';
    static public String EMAIL_STATUS_SENT = 'Sent';
    static public String EMAIL_STATUS_FORWARDED = 'Forwarded';
    static public String EMAIL_STATUS_DRAFT = 'Draft';
    
    
    
}