public with sharing class ProblemOrderConstants
{
    public static final String PROBLEM_CASE_ERROR_MESSAGE = 'Unable to create task for problem order';
    public static final String PROBLEM_CASE_2ND_EMAIL_ERROR_MESSAGE = 'Unable to send 2nd email';
    public static final String PROBLEM_CASE_RECORD_TYPE = 'Problem_Case';
    public static final String REVISION = 'Revision';
    public static final String CLOSED_STATUS = 'Closed';
    public static final String REVISED_ORDER_RESOLUTION_REASON = 'Resolved – Revision Placed on LZ.com';
    public final static String POA = 'Power of Attorney';
    public final static String EP_BUNDLE = 'EP Bundle';
    public final static Integer SIZE = 25;
    public final static String QUEUE_NAME = 'CC PS Outgoing';
    public final static String ACTION_TYPE = 'Manual Problem Order';
    public final static String OTHER= 'Other';
    public final static String UNRESOLVED_REASON_ERROR = 'Resolution Reason cannot be provided without closing the case.';
    public final static String RESOLVED_REASON_ERROR = 'You should close the case before resolving.';
    public final static String RESOLUTION_REQUIRED = 'Problem Resolution is required.';
    public final static String RESOLUTION_OTHER_ERROR = 'Other field is requied';
    public final static String FIRST_EMAIL = '1st Email Sent';
    public final static String SECOND_EMAIL = '2nd Email Sent';
    public final static String EMAIL_TEMPLATE = 'PSD_Prod_Hold';
    public final static String UNRESOLVED_CLOSED = 'Unresolved – Auto Closed';
    public final static String REVISION_AFTER_7DAY_STATUS = 'Resolved – Revision Placed on LZ.com (After 7 Day Auto-Closure)';
}