var jsUtility = {
	makeDarkBorder : function(){
			 $(".slds-radio--faux").css('border', '1px solid #808080');
	         $(".slds-input").css('border', '1px solid #808080');
	         $(".slds-textarea").css('border', '1px solid #808080');
	         $(".slds-select").css('border', '1px solid #808080');
	         $("select").css('border', '1px solid #808080');
	         $("input").css('border', '1px solid #808080');
	}
};
